version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "4000:80"
    depends_on:
      - postgres
    networks:
      - awesome

  app:
    build:
      context: .
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    networks:
      - awesome

networks:
    awesome:
        driver: bridge
