name: 'code checks'
on:
  push:
  pull_request:
jobs:
  test-job:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '12.x'

    - name: 'install'
      run: npm i

    - name: 'test'
      run: npm run test

  build-job:
    needs: test-job
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '12.x'

    - name: 'install'
      run: npm i

    - name: 'build'
      run: npm run build
