name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run a testing in Testing
        run: echo "Hello, world from Testing job"

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Run a deploy in Deploy
        run: echo "Hello, world from Deploy job"
    
